### ISSUE TITLE
Feat:Clerk Authentication

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [vansh-codes/Gityzer#11]
### Describe the feature

Want to Integrate Clerk Authentication for this app.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/7882f1f0-696f-46db-b766-a28f3b6bc2c2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
We don't need authentication in this repository dude!
You can search for some other issues which I will be happy to assign
