### ISSUE TITLE
BUG: mobile responsiveness

### ISSUE THREAD

**Issue by Sourabh782** [vansh-codes/Gityzer#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The sites not responsive for mobile
![Screenshot_20241008_063606_Chrome](https://github.com/user-attachments/assets/034856da-6cb8-42b4-8339-cb1ae1e9245e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [X] I'm a Hacktoberfest'24 registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Go ahead 🚀
