### ISSUE TITLE
Revamp the UI for a Modern, Interactive, and User-Centric Experience

### ISSUE THREAD

**Issue by 770navyasharma** [vansh-codes/Gityzer#16]
Hi, I’d love to contribute by completely revamping the UI to enhance the overall user experience! The current UI is functional but could be transformed into something visually appealing and highly interactive. Example ideas :

<img width="1407" alt="Screenshot 2024-10-03 at 6 18 33 AM" src="https://github.com/user-attachments/assets/d2e02efb-4a4c-471f-abc9-31920decf392">

<img width="1407" alt="Screenshot 2024-10-03 at 6 17 40 AM" src="https://github.com/user-attachments/assets/2f84ebec-2f0d-4b0c-aa2d-01f687e771cf">

**Comment by vansh-codes** [comment]
Wow cool!
Create a new page `Who Are We` and make it there and add its link in the main page top right at the marked place
- Make it responsive for all screen sizes

![image](https://github.com/user-attachments/assets/f5d81a87-7af7-4994-af37-485d5ae97a03)

happy contributing!
For any doubts or the content needed to write in the page, feel free to comment here or create a new discussion [here](https://github.com/vansh-codes/Gityzer/discussions)

**Comment by vansh-codes** [comment]
@770navyasharma make sure to follow the theme from the main page, don't use the green theme as seen in the screenshots shared by you

**Comment by vansh-codes** [comment]
Are you still willing to work on this or shall we close this issue??

**Comment by Supratim69** [comment]
Can i pick this up?

**Comment by vansh-codes** [comment]
@770navyasharma Are you willing to do this or shall I assign @Supratim69  ??

**Comment by PriyanshuValiya** [comment]
@vansh-codes What's the status of this issue, i want to work on it and i'll submit this the next day after assigning this issue..

**Comment by vansh-codes** [comment]
@Supratim69 Do you wanna work on this issue as @770navyasharma is not responding

**Comment by Supratim69** [comment]
Yes I'll take it up

**Comment by vansh-codes** [comment]
@Supratim69 go ahead 🚀

**Comment by Supratim69** [comment]
can I get the content of this?
