### ISSUE TITLE
Feat: Setup AI model to begin AI integrity ⚙️

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/Gityzer#19]
### Describe the feature

As described in the [README](https://github.com/vansh-codes/Gityzer/README.md), its time to start working on AI to take GITYZER a step ahead and start focusing on what matters
Set up AI in this repository following best practices & folder structure
Anyone who does this task effectively will be rewarded `level3` 🎊 
Initial setup includes:
- setting up AI folder to start working with GEMINI API
- on going to `/<username>`, a unique random tagline should be generated by the Gemini AI

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by garimabhayanaa** [comment]
I would like to be assigned the task.

**Comment by vansh-codes** [comment]
You are assigned, I hope you are skilled in this task and will take care of all the points I mentioned efficiently!

**Comment by murtaza-sadri-19** [comment]
Hi @vansh-codes, In this do we need to work with Gemini API and integrate it to **GITYZER** or just develop an AI based model ?

**Comment by vansh-codes** [comment]
Have you read and understood what Gityzer is all about??
We will be fetching alot of data from users github api and summarizing it using the trained model to generate unique taglines based on their github stats
Is it possible and feasible to create and train our own model for this?

**Comment by murtaza-sadri-19** [comment]
> @murtaza-sadri-19 Have you read and understood what Gityzer is all about?? We will be fetching alot of data from users github api and summarizing it using the trained model to generate unique taglines based on their github stats Is it possible and feasible to create and train our own model for this?
> 
> This unique tagline can be used by users in their readme and it will make every user stand out with a unique customized tagline for themself

Yes, it's definitely possible to train a custom model for this task. However, it would require significant research and experimentation to determine the optimal model architecture, data requirements, and training parameters. Given the complexity of the task and the potential challenges involved, I'm not entirely confident in my ability to successfully train a model to do the needy task.
That being said, I'm eager to explore this possibility further and would be interested in potentially developing a highly accurate and effective model that generates unique taglines based on users' GitHub stats.

**Comment by garimabhayanaa** [comment]
I am almost done with the code for tagline generation, @vansh-codes should i do image generation too or it will be done later?

**Comment by vansh-codes** [comment]
We will do it in another issue, first complete this and create PR so I can review it, if everything is fine then I will tell you so you can create new issue for image generation

**Comment by vansh-codes** [comment]
> > @murtaza-sadri-19 Have you read and understood what Gityzer is all about?? We will be fetching alot of data from users github api and summarizing it using the trained model to generate unique taglines based on their github stats Is it possible and feasible to create and train our own model for this?
> > 
> > This unique tagline can be used by users in their readme and it will make every user stand out with a unique customized tagline for themself
> 
> Yes, it's definitely possible to train a custom model for this task. However, it would require significant research and experimentation to determine the optimal model architecture, data requirements, and training parameters. Given the complexity of the task and the potential challenges involved, I'm not entirely confident in my ability to successfully train a model to do the needy task.
> That being said, I'm eager to explore this possibility further and would be interested in potentially developing a highly accurate and effective model that generates unique taglines based on users' GitHub stats.

I highly appreciate your efforts! Lets wait for @garimabhayanaa to complete the task then we can decide how to move further.. 
I am highly impressed by your clarity and honesty

**Comment by dishasharma18** [comment]
HEY CAN I ALSO GET THE TASK!

**Comment by vansh-codes** [comment]
Hii @murtaza-sadri-19, we are facing some issues in the AI working, can you help it fixing?
#22 this was the PR

**Comment by murtaza-sadri-19** [comment]
> Hii @murtaza-sadri-19, we are facing some issues in the AI working, can you help it fixing? #22 this was the PR

Yeah, sure. I'll create a new issue for that.Will that be okay ?

**Comment by vansh-codes** [comment]
Sure sure @murtaza-sadri-19 
Please fix the errors and make it work as soon as possible!

**Comment by murtaza-sadri-19** [comment]
@vansh-codes, I have started a new issue #29, please assign me so that I could start the PR. I have resolved the issues.
