### ISSUE TITLE
Feat: Initial Page Setup Enhancement

### ISSUE THREAD

**Issue by Tamanna225** [vansh-codes/Gityzer#2]
### Describe the feature

I would like to propose enhancement for the initial Page creating a UI for the initial page by taking the inspiration form Github Socialify.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Go ahead 🚀

**Comment by Rashigera** [comment]
Kindly assign this to me

**Comment by vansh-codes** [comment]
Its already assigned @Rashigera 
Kindly search for new issues or feel free to create one!
