### ISSUE TITLE
Feat: Design Logo for Gityzer

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/Gityzer#20]
### Describe the feature

Gityzer is looking for someone who can desgin unique, creative, attractive and meaningful logo  
NOTE:
- design rough designs first then on approval go for final designing
- multiple drafts can be asked for this task so be ready for changes everytime
- changes will be asked everytime when improvement will be needed
- professional logo

**LEVEL3 TASK**
- Multiple designers can take up this task, best one will be considered and awarded level3

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by garimabhayanaa** [comment]
i would like to be assigned the task

**Comment by vansh-codes** [comment]
You can work on it, as I mentioned, this can be took up by multiple contributors and I will be selecting the best and assigning them
You can design multiple rough drafts and share here for confirmation

**Comment by garimabhayanaa** [comment]
A suggested design- 
<img width="659" alt="logo" src="https://github.com/user-attachments/assets/3d3e60bf-6223-4e17-87ee-94dcb1369aae">

**Comment by vansh-codes** [comment]
Can we get a logo? a circular unique design instead of the name!
This one is also good, the tagline is great

**Comment by garimabhayanaa** [comment]
Noted. I'll make the required changes and share as soon as possible.

**Comment by garimabhayanaa** [comment]
Updated design suggested to fix #20
![G-final](https://github.com/user-attachments/assets/8c2b59e4-b17d-460f-82e4-811bcf35a561)

**Comment by vansh-codes** [comment]
Would be better if we remove the red blue fade design from text and keep it simple black, do the changes

**Comment by vansh-codes** [comment]
also create a draft with white color, text and logo in white color with transparent background

**Comment by vansh-codes** [comment]
I can see black background behind github logo on the white logo draft, can we remove that? Because it will look odd!
Remove that and then you can create PR, create a high quality .ico, .svg, .png and .webp of both the logos named
dark-logo for dark 
light-logo for light
And favicon.ico for the favicon

Do all this and create PR
