### ISSUE TITLE
Add a custom favicon

### ISSUE THREAD

**Issue by AyushSharma72** [vansh-codes/Gityzer#26]
### Describe the feature

the current icon is a vercel icon i will create and add a favicon for the website 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/59d2b2c6-3637-4613-bfd2-0ee4c6b9dfc2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
logo for favicon is already being created #20

**Comment by vansh-codes** [comment]
You can close the issue as its duplicate
