### ISSUE TITLE
Feat: Setup AI model to Generate Tagine

### ISSUE THREAD

**Issue by murtaza-sadri-19** [vansh-codes/Gityzer#29]
### Describe the feature

A GitHub User Tagline Generator will use GenAI to analyze user profiles and generate personalized taglines. These taglines will be relevant, engaging, and customizable, enhancing user profiles and attracting potential collaborators and employers. The feature will be integrated into the GitHub user interface and provide a personalized experience.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Sure please create a PR

**Comment by murtaza-sadri-19** [comment]
Please assign me labels as well @vansh-codes and I have sent a PR as well

**Comment by vansh-codes** [comment]
Completed
