### ISSUE TITLE
Doc Update: Add auto-comment bot on new issue

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/Gityzer#3]
### Describe the Documentation Update

I want a auto-comment bot on this repo which will comment when a new issue is created
Message should be:
`👋 Thanks for opening this issue! We appreciate your contribution. Please make sure you’ve provided all the necessary details and screenshots, and don't forget to follow our Guidelines and Code of Conduct. Happy coding! 🚀`

A bot comment when issue is closed
Message should be:
`✅ This issue has been successfully closed. Thank you for your contribution and helping us improve the project! If you have any more ideas or run into other issues, feel free to open a new one. Happy coding! 🚀`

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this documentation issue

**Comment by adityakalburgi** [comment]
Hi! @vansh-codes i can do this please assign it to me!

**Comment by vansh-codes** [comment]
You are assigned 🚀

**Comment by adityakalburgi** [comment]
hello @vansh-codes i have submitted a PR please have a look!

**Comment by vansh-codes** [comment]
Done ✅
