### ISSUE TITLE
**HIGH PRIORITY** BUG: FIX AI TAGLINE generation

### ISSUE THREAD

**Issue by vansh-codes** [vansh-codes/Gityzer#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

![image](https://github.com/user-attachments/assets/da4654f9-b033-4a63-9ab7-21a24cd76bc2)

Fix the code to make this work

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [X] I'm a Hacktoberfest'24 registered Contributor
- [X] I want to work on this issue

**Comment by Sourabh782** [comment]
hii @vansh-codes can i work on this issue?

**Comment by vansh-codes** [comment]
@Sourabh782 Its 2 days no update? No PR ?
Are you fixing this or shall I assign someone else?

**Comment by Sourabh782** [comment]
Hii @vansh-codes I was working on it, will send pr tommorow 👍👍, it gpt a little late dur to festive 🥲

**Comment by vansh-codes** [comment]
Sure then will be waiting for your PR tomorrow

**Comment by Sourabh782** [comment]
@vansh-codes found a bug in generateTagline.js file

fixed some errors, working on other

![image](https://github.com/user-attachments/assets/86ee2f9c-05d5-4df5-b2e8-204ca1d46551)

**Comment by Sourabh782** [comment]
Hii @vansh-codes, i fave fixed the issue :
![image](https://github.com/user-attachments/assets/04848e6c-ff6d-4450-94c9-fdcd06322ba0)


https://github.com/user-attachments/assets/d82132d4-1587-4d77-8c8f-7c5877fc5981

is it ok ?

**Comment by vansh-codes** [comment]
Looks good now!
Lets see after merging

**Comment by vansh-codes** [comment]
Create a pull request so I can review it
