### ISSUE TITLE
BUG: **High Priority** Getting "Application error: a client-side exception has occurred (see the browser console for more information)." when typed any github username.

### ISSUE THREAD

**Issue by GunaVardhanaReddyT** [vansh-codes/Gityzer#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

when we type any username in the type any username section of home page and click on the button , there is an error page displaying "**Application error: a client-side exception has occurred (see the browser console for more information).**. adress and resolve this issue as early as possible. 
![image](https://github.com/user-attachments/assets/5d3cd687-c517-4a50-9728-fc8e75087ffd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [ ] I'm a Hacktoberfest'24 registered Contributor
- [ ] I want to work on this issue

**Comment by tarunkumar2005** [comment]
@vansh-codes I can work on this issue assign this to me under gssoc 2024 ext and hacktoberfest

**Comment by vansh-codes** [comment]
@GunaVardhanaReddyT Yes theres an error with it which was supposed to be fixed by #32 but still its not done, if within 24 hours I dont get any reply from him then I will asign that to you
