### ISSUE TITLE
Adding the 404 page

### ISSUE THREAD

**Issue by G-Rajashekar** [vansh-codes/Gityzer#34]
I can add a 404 page like this:
![Screenshot (444)](https://github.com/user-attachments/assets/ff6ea5a3-7ef5-4323-98e9-03d20ec84d54)

**Comment by G-Rajashekar** [comment]
can you assign this issue to me with labels gssoc-ext and hacktoberfest

**Comment by vansh-codes** [comment]
On which urls this page will be displayed, share some invalid url's please

**Comment by vansh-codes** [comment]
To your information, the url will be updated dynamically and there would be a check for valid and invalid urls so we dont need a 404 page in this
Sorry for this time!
You can search for some other issue which I would be happy to assign
