### ISSUE TITLE
Feat: Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [vansh-codes/Gityzer#35]
### Describe the feature

Adding the contributors page to mention all the awersome people who have contributed to the website.

### Add ScreenShots

@vansh-codes Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Its already there, you can check https://github.com/vansh-codes/Gityzer/CONTRIBUTORS.md

**Comment by tarunkumar2005** [comment]
@vansh-codes On website there is more changes of networking and getting people found never mind if you don't want it in your website.
