### ISSUE TITLE
Doc Update: Update README for Enhanced Appeal and Contributor Section

### ISSUE THREAD

**Issue by AnushkaChouhan25** [vansh-codes/Gityzer#37]
### Describe the Documentation Update

Propose to enhance the README file by making it more engaging and visually appealing. Additionally, include a contributor section similar to the one in the provided image to acknowledge the contributors effectively.

### Add Screenshots 
![image](https://github.com/user-attachments/assets/76d67781-e836-4636-8709-b64c3053ae08)

### Confirm

-  I agree to follow this project's Code of Conduct
-  I'm GSSOC'24 Extd registered Contributor
-  I'm Hacktoberfest registered Contributor
-  I want to work on this documentation issue

**Comment by vansh-codes** [comment]
We already have a separate file for contributors
Check [here](https://github.com/vansh-codes/Gityzer/blob/master/CONTRIBUTORS.md)

Closing the issue as its invalid and not required
