### ISSUE TITLE
UI Modernization: Add Footer and Animations

### ISSUE THREAD

**Issue by Mallik-vinukonda** [vansh-codes/Gityzer#39]
I’ve noticed that the repository is missing a footer and the overall user interface could use some modernization. I plan to add a clean and consistent footer, while also updating the UI for a more modern and polished look. Additionally, I will incorporate animations to enhance user interactions and improve the visual appeal of the site.

Let me know if you have any specific design ideas or preferences!

**Comment by vansh-codes** [comment]
Footer is not required for this website, if you have any other ideas create a new issue which I will be happy to assign
I am closing this one!
