### ISSUE TITLE
Feat: will Add dark mode support that dynamically adjusts based on the user's system preferences

### ISSUE THREAD

**Issue by adityakalburgi** [vansh-codes/Gityzer#4]
### Describe the feature

The Dark Mode Support feature allows users to switch between light and dark themes based on their system preferences or manually through a toggle. This improves the user experience by making the interface easier on the eyes, especially in low-light environments.

### Add ScreenShots

The Dark Mode Support feature allows users to switch between light and dark themes based on their system preferences or manually through a toggle. This improves the user experience by making the interface easier on the eyes, especially in low-light environments also will add screenshot on how it works after project assign.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Go ahead 🚀
theere should be a dropdown, with 3 options
- system
- light
- dark

by default set to system theme
if you cant implement system theme then its fine just do light and dark theme

**Comment by vansh-codes** [comment]
@adityakalburgi The code is updated, you can start working

**Comment by vansh-codes** [comment]
Hey @adityakalburgi 
Have you started working?

**Comment by vansh-codes** [comment]
I feel only dark mode would be enough for Gityzer so if we can drop this idea and you can search for some other issues?

**Comment by adityakalburgi** [comment]
hi @vansh-codes i have already completed the implementation of dark mode in project....

**Comment by vansh-codes** [comment]
Dont go with light mode implementation, share a video of dark mode implementation and then you can create PR
