### ISSUE TITLE
Verified GitHub Profile Insights: Contribution Summary & Tech Specialization

### ISSUE THREAD

**Issue by Mallik-vinukonda** [vansh-codes/Gityzer#40]
### Describe the feature

We propose enhancing the tool by adding a Contribution Summary and Language Statistics section.

Contribution Summary: Display the total number of contributions (commits, pull requests, issues), the number of active coding days in the past year (from the contributions calendar), and the user’s longest contribution streak. This gives users a clear view of their coding consistency and overall activity.

Language Statistics: Show the user’s most used programming languages in a visual format (e.g., pie chart or bar graph), and highlight their specialization (front-end, back-end, or full-stack development) based on their tech stack.

These features will provide users with a comprehensive and visually appealing summary of their GitHub contributions and expertise.

### Add ScreenShots

....

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
It doesnt meets the requirements of the website and its purpose, its a addon for which there are already many websites and ways. Sorry for this time! 
Closing the issue..
