### ISSUE TITLE
Image and Username can also be shown there

### ISSUE THREAD

**Issue by Aditya-edith** [vansh-codes/Gityzer#41]
### Describe the feature

Can add one Option in UI which will shows the Profile of the particular user and their name

### Add ScreenShots

![image](https://github.com/user-attachments/assets/bbd6dd31-2e28-49ea-8ca8-c84a32cbd879)
here as we have large empty space here we can add image and username

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Read the README file, we have to generate images like this ⬇️ 

![](https://github-readme-stats.vercel.app/api?username=vansh-codes&theme=dark&hide_border=true&include_all_commits=true&count_private=false)

using the URL -> https://github-readme-stats.vercel.app/api?username=vansh-codes&theme=dark&hide_border=true&include_all_commits=true&count_private=false

This is the motive that we will generate images like this from the URL so we dont need users image for this, but yes we need username but in the image I have given above

Can you do this task? A image will be generated depending upon the values in the URL ?

**Comment by Aditya-edith** [comment]
yeah i can try

**Comment by Aditya-edith** [comment]
ASSIGN ME HERE @vansh-codes

**Comment by vansh-codes** [comment]
Level will be assigned later seeing your work

**Comment by Aditya-edith** [comment]
can't find the CORS policy.
error in console regarding the same blocked 3000 localhost CORS

**Comment by Akshithsaai** [comment]
@vansh-codes I would like to work on this . Please assign me this issue.

**Comment by vansh-codes** [comment]
Can you generate img from link? As I have described in above comments

**Comment by Akshithsaai** [comment]
![image](https://github.com/user-attachments/assets/99e8f8d8-9df7-47ac-8afe-17d37d97168c)

You mean similar to this this image ryt ? @vansh-codes

**Comment by vansh-codes** [comment]
Yes!

**Comment by vansh-codes** [comment]
Can you do the setup for this? for now keep image and few details in the image @Akshithsaai

**Comment by Akshithsaai** [comment]
Yeah I can do this @vansh-codes

**Comment by vansh-codes** [comment]
Go ahead @Akshithsaai

**Comment by vansh-codes** [comment]
@Akshithsaai Open a new issue for this one
