### ISSUE TITLE
Feat: Implementation User Profile Card | Containing User's Data

### ISSUE THREAD

**Issue by Shariq2003** [vansh-codes/Gityzer#42]
### Describe the feature

I want to implement the Github User profile Card that will be shown to user when a username entered.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/1659ca98-0382-4d0f-bc11-9f703c3e113e)

Like this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Hey! Did you read the `README.md` ??

**Comment by Shariq2003** [comment]
> Hey! Did you read the `README.md` ??

Oops, sorry, not read at the time of issue creation, but have read now and understand.
