### ISSUE TITLE
Feat: Submit button 

### ISSUE THREAD

**Issue by Zubaida0113** [vansh-codes/Gityzer#47]
### Describe the feature

Hey @vansh-codes, I want to add a Next/Submit button on this page to move forward to the next page. I would also like to make the background consistent with the first landing page background(which is a blue gradient in colour). 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/92f4b593-2f0f-48b9-a9ca-a8fff4b3f6d0)
As there is no button to move forward.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Have you read the `README.md` file?
If yes then you should be knowing the purpose and motive of the project 
It doesnt needs any `next` btn

**Comment by Zubaida0113** [comment]
Hey Vansh,

I’ve reviewed the README.md file thoroughly and fully understand the project's purpose and scope. The project is indeed focused on fetching GitHub data, generating taglines using the Gemini AI model, and creating customized images for users' profiles, all in a dynamic and personalized way.

That being said, the suggestion for a "Next" button may still have merit, depending on the user flow we want to provide. While it may not be part of the core functionality as per the README, it could enhance the user experience by offering more intuitive navigation or a step-by-step process for users who prefer a guided approach.

I’m happy to discuss whether it could be an optional feature that adds value to certain use cases. Let me know what you think!

**Comment by vansh-codes** [comment]
ahh @Zubaida0113 I like your thought and idea but I think its not required in this
Would you like to work on something like please let me know your skillset

**Comment by Zubaida0113** [comment]
Thanks for the feedback; I appreciate it! I'd be happy to work on something more relevant to the project. My expertise includes frontend technologies like HTML, CSS, and JavaScript, and I also have experience in Java and Python. If there's a part of the project where these skills can be useful, especially on the front end, feel free to let me know!

**Comment by vansh-codes** [comment]
It doesn't meets the requirements of the project, do you know Ai Ml in python?
