### ISSUE TITLE
Feat: Integrate a Chatbot for Instant User Support 

### ISSUE THREAD

**Issue by sezallagwal** [vansh-codes/Gityzer#48]
### Describe the feature

Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

### Add ScreenShots

Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Have you read the `README.md` file?
Chatbot is not required for this project
Sorry for this time!
Search or Create another issues which I will be happy to assign
