### ISSUE TITLE
Doc Update: Contributors not showing

### ISSUE THREAD

**Issue by yashksaini-coder** [vansh-codes/Gityzer#5]
### Describe the Documentation Update

I want to integrate an action workflow that will be used to fetch & display the contributors profile in the contributor section of the README. 

It will enhance the overall engagement of the new contributors in your project.

@vansh-codes I want to work on this issue can you assign it to me & add labels to it. 

### Add Screenshots (if applicable)

**Before:-**

- ![image](https://github.com/user-attachments/assets/085cc5c1-e5b7-4812-88ed-b8f4f3300b28)

**After:-**

- 
![image](https://github.com/user-attachments/assets/617f8784-9206-42f7-8f24-cf87585f862e)

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this documentation issue

**Comment by vansh-codes** [comment]
Hey @yashksaini-coder, We can create a new CONTRIBUTORS.md for this and there you can use the workflow to fetch all contributors
Dont implement this in the README.md
For any doubts, feel free to comment here again or raise a discussion
