### ISSUE TITLE
Feat: Improve design of error 404 page

### ISSUE THREAD

**Issue by dev129** [vansh-codes/Gityzer#50]
### Describe the feature

Hi @vansh-codes 
**Description:**
The current error page displays a generic message ("The future of GitHub is here" and similar phrases) that does not align with our branding and user experience standards. A more visually appealing and informative error page is needed to enhance user engagement and provide clearer guidance.

**Proposed Changes:**
1. **Visual Design:** Create a more modern, cohesive design that matches our overall website aesthetic.
2. **User Guidance:** Include helpful links (e.g., home page, contact support) and a friendly message.
3. **Branding Elements:** Incorporate our logo and color scheme to maintain brand consistency.

**Additional Notes:**
A well-designed error page can significantly improve user experience and reduce frustration. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/30e79677-cdfe-450a-9c7b-fa94ccae5c82)
I can make it look better

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by dev129** [comment]
Hi @vansh-codes 
This is the final design, tell me how it looks 
![Uploading image.png…]()
Also if you have a logo in mind please tell me I shall induce that logo in the page.

**Comment by vansh-codes** [comment]
Use illustrations instead of image, everything else is fine

**Comment by dev129** [comment]
Hi @vansh-codes 
![image](https://github.com/user-attachments/assets/29ed74a0-3e3f-4e3b-85bb-57718ace31b9)

This is the final design, waiting for PR approval.

**Comment by vansh-codes** [comment]
Yeah works! create a PR and dont forget to mention this issue in your PR
