### ISSUE TITLE
Feat: Home icon on all pages

### ISSUE THREAD

**Issue by Unnati2603** [vansh-codes/Gityzer#56]
### Describe the feature

I want to add your icon to all pages, so that when the user clicks on it , they are redirected to the home page.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e1272a85-6ef6-41b8-aba9-acced2a7401f)
this is where i want to add you icon redirecting to the home page

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
add it on top left

**Comment by Unnati2603** [comment]
Hey! I completed it. Check it out. If its fine, I will make a pull req.


https://github.com/user-attachments/assets/489006c4-28b3-4aae-a717-bc3053afb125
