### ISSUE TITLE
Feat:Animated Website Name

### ISSUE THREAD

**Issue by akash70629** [vansh-codes/Gityzer#57]
### Describe the feature

I want to make the name of the website attractive by animating it.

### Add ScreenShots

https://github.com/user-attachments/assets/3d599216-f1f6-4230-bec9-3be83c1a3aec

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by akash70629** [comment]
please assign me this issue under gssoc label .

**Comment by vansh-codes** [comment]
Instead of website name, do it here ⬇️ 

![Screenshot 2024-10-29 163648](https://github.com/user-attachments/assets/5613be71-101f-4bbb-9bc3-61cadb873154)
