### ISSUE TITLE
Feat: Fetching and displaying User's Github data

### ISSUE THREAD

**Issue by piyushpatelcodes** [vansh-codes/Gityzer#58]
### Describe the feature

# Gityzer Feature Suggestion

## 📜 User Information Display

- Displays essential GitHub profile information, including:
  - **Username**
  - **Location**
  - **Follower Count**
  - **Following Count**
  - **Public Repositories**

## ⚡ Real-Time Loading Indicators

- Shows a loading indicator while fetching profile data from the GitHub API to enhance the user experience.

## 📈 Scalability & Future Enhancements

- Designed for future growth with planned features, including:
  - **Followers/Following List**: Display followers and following users in a user-friendly format.
  - **Gists Display**: Show user-created gists if available.
  - **User Events/Orgs**: Highlight recent GitHub activities and contributions, especially in organizations.

  
Stay tuned for more updates as we continue to enhance the Gityzer!
If You allow me i can add All the future enhancements by this october ends.

### Add ScreenShots

https://github.com/user-attachments/assets/88662532-f076-475f-a8e5-0690a5b24af0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Looks awesome!
