### ISSUE TITLE
Feat:Add text Animation to home page

### ISSUE THREAD

**Issue by gurliv21** [vansh-codes/Gityzer#6]
### Describe the feature

I would like to suggest adding a text animation to the word "GITYZER" on the homepage. I believe this addition could enhance the visual appeal and engagement of the site.

### Add ScreenShots

<img width="1249" alt="Screenshot 2024-10-07 at 3 56 28 PM" src="https://github.com/user-attachments/assets/67667a9c-d5a1-4e78-bf0e-539a6704e743">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
The first page is still not setup, its just kept as a placeholder
#2 will be setting up the page then you can work on adding animations
I will update you on this till that time you can search for another issues!

**Comment by Ek-ta-bharti** [comment]
I would like to work on this. Please assign this to me.

**Comment by vansh-codes** [comment]
Its already assigned to @gurliv21 , its just that we are waiting for #2 to be completed so then I will assign him

**Comment by vansh-codes** [comment]
@gurliv21 you can now see for any enhancements in the main page and start working!
