### ISSUE TITLE
Feat: Adding Dockerfile for easy usage/installation of Project in any environment

### ISSUE THREAD

**Issue by mayank-0407** [vansh-codes/Gityzer#60]
### Describe the feature

We can add a Dockerfile to easily use this project in an isolated container, and run the project with 1 command.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2a2297a6-80aa-497b-821c-4d3df1ffbdb0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Can you please explain more about it? what changes does it do? what are the advantages and how will it impact? Will there be any prerequisites for contributors after we do this?

**Comment by mayank-0407** [comment]
@vansh-codes 
Adding a Dockerfile will allow the project to run in an isolated container, making setup simple and consistent. With this, contributors can start the project with just one command (docker build and docker run), minimizing dependency issues by ensuring everyone works in the same environment.

Impact: Smoother onboarding, reduced setup issues, and improved cross-system compatibility.
Prerequisites: Contributors will need Docker installed, but no other changes to the current workflow are required.

**Comment by vansh-codes** [comment]
Brother not everyone has dockers installed, even i dont have dockers installed in my system, i guess it will force the contributors to install dockers first making it more complex for them which will hinder the contribution rate in the project
You had a great idea but it doesnt aligns with the project for now
Look for other issues which I will be happy to assign
I am closing this issue for now

**Comment by mayank-0407** [comment]
@vansh-codes Adding a Dockerfile provides an optional, flexible way to run the project in an isolated container without requiring Docker for existing workflows. Contributors can continue running the project as usual or use Docker if they prefer. This setup especially helps in future scenarios, like Node.js version mismatches, ensuring a consistent environment and eliminating compatibility issues.

Impact: Docker offers smoother onboarding and cross-system compatibility, while staying optional for contributors.
Future Benefit: Docker becomes invaluable if/when dependencies like Node.js version mismatches arise, as it ensures the project runs consistently across all setups.
