### ISSUE TITLE
🐞BUG: Submit Button Enabled Despite Empty Username

### ISSUE THREAD

**Issue by akash70629** [vansh-codes/Gityzer#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The submit button remains enabled and clickable even when the username input field is empty. Although an error message is displayed, the button should be disabled to prevent unnecessary submissions.

## Reproduction Steps:

1. Open the Website.
2. Clear the username input field.
3. Click the submit button.

## Expected Behavior:
The submit button should be disabled when the username input field is empty.

## Actual Behavior:
The submit button remains enabled and clickable, allowing users to submit an empty username.

## Screenshot 
![image](https://github.com/user-attachments/assets/75911fa0-9518-4859-87b2-3ee7d8d1a032)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [X] I'm a Hacktoberfest'24 registered Contributor
- [X] I want to work on this issue

**Comment by akash70629** [comment]
Please assign me this issue.

**Comment by vansh-codes** [comment]
Though its enabled, we have kept an error msg as you can see in the screenshot provided by you as well, so no need of disabling the btn
I am closing this issue, please search for another relevant issues which I would be happy to assign
