### ISSUE TITLE
Feat: UI/UX Improvement: Enhance Button Styling and Alignment

### ISSUE THREAD

**Issue by Aditiiii-pathak** [vansh-codes/Gityzer#65]
### Describe the feature

The buttons across the Gityzer website currently lack consistent styling and alignment, leading to a slightly disjointed user experience. Improving the button design and alignment would create a more cohesive, visually appealing interface, enhancing the user’s navigation experience

**Details:**
**Proposed Style Enhancements:**

**Color Scheme:** Adopt a consistent color scheme that aligns with the site's branding. A primary and secondary color palette would improve visual consistency.
**Button Shape: U**se rounded corners or shadows to make buttons more modern and engaging.
**Hover Effects:** Add subtle hover effects (like color change or shadow increase) to give buttons a more interactive feel.
Alignment Suggestions:

Ensure buttons are centrally aligned within their sections for a cleaner layout.
Adjust spacing between buttons and other elements for a balanced look on different screen sizes.

**Benefits:**
Enhanced Aesthetic: Consistent styling will improve the visual flow of the site.
Better Usability: Aligned, well-spaced buttons are easier to click and create a more intuitive navigation experience.
Improved Engagement: Visually appealing buttons encourage users to interact with different sections of the website.

**Suggested Approach:**
CSS Enhancements:
Use CSS properties like border-radius, box-shadow, and transition to enhance button styling.
Responsive Alignment:
Apply responsive design principles with CSS Grid or Flexbox to maintain button alignment on various devices.

### Add ScreenShots

![Screenshot 2024-10-30 001007](https://github.com/user-attachments/assets/1640921c-22e2-4c76-bfef-6635c2f863f0)
![Screenshot 2024-10-30 001039](https://github.com/user-attachments/assets/b40aca6e-8822-46a5-8613-4536fba71a93)

Want to add:
Search Repository Feature
Enhanced Styling for Buttons
Improved Profile Page Layout
Add Visual Indicators and Feedback

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [ ] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
The landing page is fine for now, in the next page, the screenshot you shared about the background color changing btn, that part has to be removed, so I think your issue is not relevant at the moment
