### ISSUE TITLE
Feat: Add more description to the repos

### ISSUE THREAD

**Issue by shar2710** [vansh-codes/Gityzer#67]
### Describe the feature

the number of commits, pull requests, whether a repository has been forked shows community interest and potential external contributions and license information. These descriptions and stats collectively enhance a repository’s usability, maintainability, and community engagement. these must also be displayed .

please assign me with this @vansh-codes . i'd like to work on this

### Add ScreenShots

<img width="903" alt="{62B23877-B28D-4540-B0B8-2D361BD5358A}" src="https://github.com/user-attachments/assets/34f99db5-6a24-430a-b984-e20a7b252ecb">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Where will you be adding all these, please provide a design idea

**Comment by shar2710** [comment]
![Screenshot_20241030_022559_Chrome.jpg](https://github.com/user-attachments/assets/794c7258-aa24-4ca6-8682-47ebbc001159)

something similar to this
