### ISSUE TITLE
Doc Update: Add "Back to Top" Scroll Button in README

### ISSUE THREAD

**Issue by T-Fathima** [vansh-codes/Gityzer#68]
### Describe the Documentation Update

Currently, the README file does not include a "Back to Top" button, making it difficult for users to navigate back to the beginning after scrolling through lengthy sections. Adding a "Back to Top" link at the end of readme file will improve navigation, providing a better user experience for readers.

@vansh-codes I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this documentation issue

**Comment by vansh-codes** [comment]
I can assign you but be aware that I cant give you any level labels for this
