### ISSUE TITLE
Feat: Featuring all the contributors on the page 

### ISSUE THREAD

**Issue by Akshithsaai** [vansh-codes/Gityzer#75]
### Describe the feature

All the Contributors of the project will be displayed on the page in carousel or card format . 

@vansh-codes You can suggest the format for me to proceed on. 

I wish to extract the info using github API and display according with good UI . 

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by Akshithsaai** [comment]
https://github.com/user-attachments/assets/16286c46-8938-4e0f-be6a-a1807dacb46e

@vansh-codes Check it out and tell if any changes are there . 
Else I can raise a PR.

**Comment by vansh-codes** [comment]
Create a separate dedicated page for contributors, create route `/contributors`
Put its link in the footer
`Open Source ❤️ | Contributors | Gityzer`

**Comment by Akshithsaai** [comment]
Ok @vansh-codes I Will do that and update you .

**Comment by vansh-codes** [comment]
Sure @Akshithsaai
Also whats the status of image generation issue?

**Comment by Akshithsaai** [comment]
@vansh-codes I have updated according your suggestion.

Please check it out .

https://github.com/user-attachments/assets/f9d5e8ea-f84d-41e8-a251-f66631e83de9

**Comment by Akshithsaai** [comment]
> Sure @Akshithsaai Also whats the status of image generation issue?

I am working on it @vansh-codes .
