### ISSUE TITLE
Feat: Display results below search bar

### ISSUE THREAD

**Issue by Akshithsaai** [vansh-codes/Gityzer#76]
### Describe the feature

Whenever a user tries to search for a user on github the should be displayed with some results so that they can search easier, faster. 

Similar to recommedation on google. 

@vansh-codes I have worked the similar issue . I can complete ASAP. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/089cedd7-1667-4337-9000-76f61011d4f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
It will increase the load on the server which I think is not required, but I have a modification idea in this, can you do it for already searched users?
For example:


**I came on the website for the first time and search for myself, then next-time I should get recommendation for my name so I can easily select, similarly last 5 searches should be displayed to the user on input box**


Let me know if you can do this task or else feel free to close the issue

**Comment by Akshithsaai** [comment]
@vansh-codes I will think about the Idea and let you know about the implementation.

**Comment by veerendra17788** [comment]
please assign me i can do that

**Comment by Akshithsaai** [comment]
@vansh-codes Check it out and suggest if any changes are there. 


https://github.com/user-attachments/assets/2e2d0fd5-d339-4b04-b3aa-4e58925c7379

**Comment by vansh-codes** [comment]
Actually we needed the suggestion type of box, when we click on input that time we should get popup kind of which we get when we fill forms and other data, this is something different :(

Can you fix it the way i am talking?

**Comment by Akshithsaai** [comment]
@vansh-codes

![image](https://github.com/user-attachments/assets/17f46861-3bcb-44bc-b7e9-ac5167f8b76e)

Is this How you want it to be ?

**Comment by vansh-codes** [comment]
Yes, but of recently searched one only

**Comment by Akshithsaai** [comment]
Ok. So whenever a user types in some input , I should display related username from search history . 
As far as I understood that, If I enter lets say 'I' , I should display names containing I from my history ryt?

@vansh-codes

**Comment by vansh-codes** [comment]
what do you mean by `my history` ?

suppose I visit the website for the first time, I search for `vansh-codes`
next time, when I click on input, i should get recommendation for `vansh-codes`
If i choose it gets into input box,
if I write some other username say `akshithsaai` then these both should come from next time, recent 5 should come maximum

**Comment by Akshithsaai** [comment]
my history is like entire usernames they searched for. 

But Yeah, Now I Understood what you are suggesting ,
You want to show top 5 recent searches as suggestions only if i click on the search input. 

Working will be same but you want the UI and functionality changed like this ryt ? @vansh-codes

**Comment by vansh-codes** [comment]
yup!

**Comment by vansh-codes** [comment]
Do it before tomorrow 7pm to get points in gssoc-ext

**Comment by Akshithsaai** [comment]
@vansh-codes Please check it out. I have made some changes.

https://github.com/user-attachments/assets/75b1aa78-4b15-4511-b011-8be24901e67a

If we click outside the input again, Suggestions will not be shown .
