### ISSUE TITLE
Doc Update : Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [vansh-codes/Gityzer#77]
### Describe the Documentation Update

Wanted to do the following changes :-

1) Enhance the project structure
2) Add star our repository section
3) Add the project structure
4) Add need help with the basics section
5) Enhance the pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the issue process section

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this documentation issue

**Comment by vansh-codes** [comment]
https://github.com/vansh-codes/Gityzer/blob/master/PROJECT_STRUCTURE.md

We already have a file for project structure, its mentioned in README.md as well, so dont create a separate one, mention this one as done in README 
Points on which you have to work as described by you in the issue description
- 2
- 4
- 5
- 6
- 7
- 8
- 9

**Comment by milansamuel609** [comment]
> https://github.com/vansh-codes/Gityzer/blob/master/PROJECT_STRUCTURE.md
> 
> We already have a file for project structure, its mentioned in README.md as well, so dont create a separate one, mention this one as done in README Points on which you have to work as described by you in the issue description
> 
> * 2
> * 4
> * 5
> * 6
> * 7
> * 8
> * 9

Sure I will work on the points that you have mentioned from my points 👍
