### ISSUE TITLE
Build a Contact Channel in readme

### ISSUE THREAD

**Issue by Varunshiyam** [vansh-codes/Gityzer#78]
### Describe the Documentation Update

To enhance communication and provide direct access to project guidance, I plan to include a dedicated Contact section. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin enabling contributors to readily connect with them and address any project-related queries.

Finally, to foster a welcoming and inclusive environment, we will incorporate personalized welcome messages for new contributors.

Kindly Assign me this Issue under labels:
- Gssoc-ext 🌸
- hacktoberfest ☘️
- Level ✨

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this documentation issue

**Comment by vansh-codes** [comment]
Theres no active mentor for this repo and my(admin's) details are already present in the readme
Thanks for the issue but its invalid for now so I am closing your issue
