### ISSUE TITLE
BUG: Repository Structure Workflow Error

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [vansh-codes/Gityzer#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The Repository Auto-Update Workflow is broken and not updating the structure:
![image](https://github.com/user-attachments/assets/cd54ed6f-8b84-4ca5-8677-ab27cb51e112)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [X] I want to work on this issue

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes Thanks for assigning the issue. I will look into the problem and let you know by tomorrow.

**Comment by vansh-codes** [comment]
Okay 🆗

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes I noticed that the workflow ran successfuly after you informed me about the issue:
![image](https://github.com/user-attachments/assets/2421f444-99b0-44ce-a70a-e360676b31f2)

I would request you merge a few more PRs and let me know if the workflow is failing. I will look into the matter meanwhile. Since I worked on this feature recently, there might be bugs that will come out eventually.

**Comment by vansh-codes** [comment]
Okay!

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes Is the workflow fine?

**Comment by vansh-codes** [comment]
Yes mostly! If there will be any errors I will contact you!
