### ISSUE TITLE
Feat: Add Navbar with Home page & Footer containing Contributors links

### ISSUE THREAD

**Issue by mehul-m-prajapati** [vansh-codes/Gityzer#84]
### Describe the feature

 Add Navbar with Home page & Footer containing Contributors links

### Add ScreenShots

![f1](https://github.com/user-attachments/assets/4d0d29d0-e4d7-43cb-87ca-9c408ed7a0cd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this issue

**Comment by mehul-m-prajapati** [comment]
@vansh-codes : please assign it to me

**Comment by vansh-codes** [comment]
No its not needed, home page is completed, minimal setup is good
