### ISSUE TITLE
Feat: Add a button  to download Github Stats of a repo

### ISSUE THREAD

**Issue by mehul-m-prajapati** [vansh-codes/Gityzer#85]
### Describe the feature

![r1](https://github.com/user-attachments/assets/2a513db0-2870-4c6d-abc6-d9293cb90bbf)

### Add ScreenShots

![c1](https://github.com/user-attachments/assets/ce09b725-5977-45f1-80f0-0eb4567d7012)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Go ahead!
