### ISSUE TITLE
Feat: Add a button to fetch Github profile stats

### ISSUE THREAD

**Issue by mehul-m-prajapati** [vansh-codes/Gityzer#89]
### Describe the feature

- Total contributions
- Participation in repositories
- Most used programming languages etc.

### Add ScreenShots

![d1](https://github.com/user-attachments/assets/59935cc1-2b6d-407d-8b3f-57a1292686bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this issue

**Comment by vansh-codes** [comment]
Go ahead, I will assign level labels after PR creation

**Comment by mehul-m-prajapati** [comment]
@vansh-codes : Do you have list of features for your project?

**Comment by vansh-codes** [comment]
Go through the issues once, if you see it pending and you want to do then comment there, if the issuer is not doing then I will assign it to you
