### ISSUE TITLE
BUG: Text is not showing in contributors page

### ISSUE THREAD

**Issue by souvikpramanikgit** [vansh-codes/Gityzer#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

The text is not showing but when i hover it then it showing , but the heading not shwing if i do hover.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 Extd Contributor
- [X] I want to work on this issue

**Comment by souvikpramanikgit** [comment]
![image](https://github.com/user-attachments/assets/1f628d25-d745-47b6-b0c3-81c6c762ab31)

**Comment by vansh-codes** [comment]
![image](https://github.com/user-attachments/assets/d514cbcb-150b-407f-bd4b-d9570cb579e9)

It is clearly visible, there might be some issue from your side i guess

**Comment by souvikpramanikgit** [comment]
![image](https://github.com/user-attachments/assets/2b4abc79-6347-48f8-9955-a37611d67f6a)

click here

**Comment by vansh-codes** [comment]
Yes its that page only, there might be some issue with your device, all the texts and everything is working fine
I am closing this issue
